spring:
  application:
    name: mscartoes
  rabbitmq:
    host: rabbitmq-3.8
    port: 5672
    username: admin
    password: admin

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@eureka-server:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


mq:
  queues:
    emissao-cartoes: emissao-cartoes
  exchanges:
    emissao-cartoes-exchange: emissao-cartoes-exchange
  bindings:
    emissao-cartoes-bindings: emissao-cartoes-bindings

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  file:
    name: ./logs/log-file-cartoes.log