version: '3.8'

networks:
  ms-network:
    name: ms-network
    driver: bridge

services:
  rabbitmq:
    container_name: rabbitmq-3.8
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=secret_pass
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    networks:
       - ms-network
  keyclock:
    container_name: keyclock
    image: quay.io/keycloak/keycloak:18.0.0
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_LOGLEVEL=INFO
      - ROOT_LOGLEVEL=INFO
    networks:
      - ms-network
    command:
      - start-dev

volumes:
  rabbitmq:

